# Generated by Django 5.1.6 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuestionario', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Modulo',
            },
        ),
        migrations.CreateModel(
            name='RecuperarContrasena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'RecuperarContrasena',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.TextField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.BigIntegerField(unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pregunta', models.CharField(choices=[('A', 'Abiertas'), ('O', 'Opcion multiples')], max_length=1)),
                ('textoopciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('Cuestionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.cuestionario')),
                ('opciones_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='appdesercion.preguntas')),
            ],
            options={
                'db_table': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repuestas', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('Preguntas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.preguntas')),
            ],
            options={
                'db_table': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('coordinador', 'Coordinador'), ('bienestar', 'Bienestar'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('comentario_coordinadorfpi', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion_coordinadorfpi', models.DateTimeField(blank=True, null=True)),
                ('comentario_coordinador', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion_coordinador', models.DateTimeField(blank=True, null=True)),
                ('comentario_bienestar', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion_bienestar', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='appdesercion.cuestionario')),
                ('bienestar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_aprobados_bienestar', to='appdesercion.usuario')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_aprobados_cf', to='appdesercion.usuario')),
                ('coordinadorfpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_aprobados_fpi', to='appdesercion.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_creados', to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Proceso',
            },
        ),
        migrations.CreateModel(
            name='Deserciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('cuestionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.cuestionario')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Deserciones',
            },
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='usuariio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.rol')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'UsuarioRol',
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.modulo')),
            ],
            options={
                'db_table': 'Vista',
            },
        ),
        migrations.CreateModel(
            name='RolVista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.rol')),
                ('vista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.vista')),
            ],
            options={
                'db_table': 'RolVista',
            },
        ),
    ]
