# Generated by Django 5.1.6 on 2025-02-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Modulo',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.TextField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuestionario', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_pregunta', models.CharField(choices=[('abierta', 'Abierta'), ('seleccion multiple', 'Seleccion multiple')], max_length=20)),
                ('textoopciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('opciones_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='appdesercion.cuestionario')),
                ('usuariio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_aprobacion', models.CharField(choices=[('coordinadorFPI', 'CoordinadorFPI'), ('coordinadorAcademico', 'CoordinadorAcademico'), ('bienestar', 'Bienestar'), ('instructor', 'Instructor')], max_length=20)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('cuestionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='appdesercion.cuestionario')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_creados', to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Proceso',
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=10, unique=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('proceso_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdesercion.proceso')),
            ],
            options={
                'db_table': 'Aprendiz',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repuestas', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('cuestionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.cuestionario')),
            ],
            options={
                'db_table': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RecuperarContrasena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'RecuperarContrasena',
            },
        ),
        migrations.CreateModel(
            name='Deserciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('proceso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.proceso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Deserciones',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('proceso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.proceso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.rol')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario')),
            ],
            options={
                'db_table': 'UsuarioRol',
            },
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.modulo')),
            ],
            options={
                'db_table': 'Vista',
            },
        ),
        migrations.CreateModel(
            name='RolVista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreo', models.DateTimeField(auto_now_add=True)),
                ('fechaModifico', models.DateTimeField(auto_now=True)),
                ('fechaElimino', models.DateTimeField(blank=True, null=True)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.rol')),
                ('vista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdesercion.vista')),
            ],
            options={
                'db_table': 'RolVista',
            },
        ),
    ]
