# Generated by Django 5.1.6 on 2025-02-12 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdesercion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperarcontrasena',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appdesercion.usuario'),
            preserve_default=False,
        ),
    ]
