# Generated by Django 5.1.6 on 2025-02-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdesercion', '0002_alter_usuario_documento'),
        ('appdesercion', '0002_recuperarcontrasena_usuario_id'),
    ]

    operations = [
    ]
